# Generated by Django 4.2 on 2023-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_authoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_record',
            name='authors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file_record',
            name='conclusion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file_record',
            name='methods',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file_record',
            name='references',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='file_record',
            name='results',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='abstract',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='document_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='introduction',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
