# Generated by Django 4.2 on 2023-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_authoring', '0002_file_record_authors_file_record_conclusion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_record',
            old_name='document_name',
            new_name='key_words',
        ),
    ]
