# Generated by Django 4.2 on 2023-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_authoring', '0003_rename_document_name_file_record_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_record',
            name='abstract',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='authors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='conclusion',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='introduction',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='key_words',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='methods',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='references',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='results',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_access',
            name='suggestion',
            field=models.CharField(max_length=3000),
        ),
    ]
